WIP : Add option to request importation of specific domains
AlternC/alternc-certbot pull request #57
Opened 2019-09-23 18:00 UTC by kienanstewart

Useful for debugging specific renewal issues

2019-12-13 20:27 UTC, kienanstewart commented
This PR is ready to be reviewed

2019-12-16 15:29 UTC, kienanstewart commented
There's one more thing that should be added here, this code path doesn't change the uid (using alternc's su) before the import. I'm not sure what the impact of that is, but I think it should use the su to match what the other code path is doing

2019-12-17 21:41 UTC, kienanstewart commented
I've added the su() for specific certificate importations.

2021-11-09 10:55 UTC, camlafit requested changes

2021-11-09 10:55 UTC, camlafit commented on src/usr/lib/alternc/generate_certbot.php
> +    $REQUEST_CERTS = 'sepcific';
Typo please correct :)

2021-11-09 10:58 UTC, camlafit requested changes

2021-11-09 10:58 UTC, camlafit commented on src/usr/lib/alternc/generate_certbot.php
> +            $sub_domain = get_sub_domain_id_and_member_by_name($domain);
it's a static method from m_dom

2021-11-09 13:18 UTC, kienanstewart commented
Hi @camlafit, thanks for the review of the proposed changes. I've fixed the elements you've highlighted. Please let me know if there's anything else.

thanks!

2021-11-09 14:15 UTC, camlafit commented on src/usr/lib/alternc/generate_certbot.php
> +            $certbot->import($domain);
add force option 
following #74

2023-05-22 11:20 UTC, camlafit commented on src/usr/lib/alternc/generate_certbot.php
> +            $certbot->import($domain);
Hello

#74 is backported to master; could you update your code to integrate force mode ?

2023-11-17 15:50 UTC, closed without merging